language: csharp
os: linux
dist: trusty
sudo: required
solution: EasyIoC.sln
mono: none
dotnet: 1.0.1
before_install:
- dotnet restore
script:
# Build all projects
- ./build.sh
# Pack for nuget
- ./push-to-nuget.sh
